/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Person": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PersonReadDtoIEnumerableApiResponse"];
                        "application/json": components["schemas"]["PersonReadDtoIEnumerableApiResponse"];
                        "text/json": components["schemas"]["PersonReadDtoIEnumerableApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PersonCreateDto"];
                    "text/json": components["schemas"]["PersonCreateDto"];
                    "application/*+json": components["schemas"]["PersonCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PersonReadDtoApiResponse"];
                        "application/json": components["schemas"]["PersonReadDtoApiResponse"];
                        "text/json": components["schemas"]["PersonReadDtoApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Person/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PersonReadDtoApiResponse"];
                        "application/json": components["schemas"]["PersonReadDtoApiResponse"];
                        "text/json": components["schemas"]["PersonReadDtoApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PersonUpdateDto"];
                    "text/json": components["schemas"]["PersonUpdateDto"];
                    "application/*+json": components["schemas"]["PersonUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PersonReadDtoApiResponse"];
                        "application/json": components["schemas"]["PersonReadDtoApiResponse"];
                        "text/json": components["schemas"]["PersonReadDtoApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BiometricReadDto: {
            /** Format: int32 */
            id?: number;
            /** Format: double */
            weight?: number;
            /** Format: double */
            height?: number;
            /** Format: double */
            bmi?: number | null;
            /** Format: date-time */
            measurementDate?: string;
            notes?: string | null;
        };
        PersonCreateDto: {
            firstName?: string | null;
            lastName?: string | null;
            nickName?: string | null;
            /** Format: date-time */
            birthday?: string;
            email?: string | null;
            phone?: string | null;
        };
        PersonReadDto: {
            /** Format: int32 */
            id?: number;
            firstName?: string | null;
            lastName?: string | null;
            nickName?: string | null;
            /** Format: date-time */
            birthday?: string;
            email?: string | null;
            phone?: string | null;
            /** Format: int32 */
            age?: number;
            createdAt?: string | null;
            updatedAt?: string | null;
            deletedAt?: string | null;
            isActive?: boolean;
            biometrics?: components["schemas"]["BiometricReadDto"];
        };
        PersonReadDtoApiResponse: {
            success?: boolean;
            message?: string | null;
            /** Format: int32 */
            statusCode?: number;
            data?: components["schemas"]["PersonReadDto"];
        };
        PersonReadDtoIEnumerableApiResponse: {
            success?: boolean;
            message?: string | null;
            /** Format: int32 */
            statusCode?: number;
            data?: components["schemas"]["PersonReadDto"][] | null;
        };
        PersonUpdateDto: {
            /** Format: int32 */
            id?: number;
            firstName?: string | null;
            lastName?: string | null;
            nickName?: string | null;
            email?: string | null;
            phone?: string | null;
            /** Format: date-time */
            birthday?: string;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
